trigger:
- master

pool:
  vmImage: "ubuntu-latest"

steps:
Settings
- task: NodeTool@
  inputs:
    versionSpec: "10.x"
  displayName: "Install Node.js"

- script: 
    npm install
  displayName: "npm install"

Settings
- task: Npm@1
  inputs:
    command: "custom"
    customCommand: "run test"

Settings
- task: PublishTestResults@2
  inputs:
    testResultsFormat: ""
